/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.view.logIn;

import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author vidan
 */
public class MainPanelLog extends javax.swing.JPanel{

    /**
     * Creates new form mainPanel
     */
    private boolean signIn;
    public MainPanelLog() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSignIn = new ui.view.logIn.PnlSignIn();
        pnlSignUp = new ui.view.logIn.PnlSignUp();
        btnSignIn = new javax.swing.JLabel();
        btnSignUp = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlSignIn.setPreferredSize(new java.awt.Dimension(410, 620));
        add(pnlSignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, -1, 620));
        add(pnlSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, -1, -1));

        btnSignIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Group 1.png"))); // NOI18N
        add(btnSignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, 210, 70));

        btnSignUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Group 2.png"))); // NOI18N
        add(btnSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, -1, 80));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/desna.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 470, 750));

        jPanel1.setBackground(new java.awt.Color(80, 109, 47));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(247, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 750));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnSignIn;
    private javax.swing.JLabel btnSignUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private ui.view.logIn.PnlSignIn pnlSignIn;
    private ui.view.logIn.PnlSignUp pnlSignUp;
    // End of variables declaration//GEN-END:variables

    
    public JLabel getSignUpButton() {
        return btnSignUp;
    }

    public JLabel getSignInButton() {
        return btnSignIn;
    }
    public JPanel getSignInPanel() {
        return pnlSignIn;
    }

    public JPanel getSignUpPanel() {
        return pnlSignUp;
    }
    
    public void switchPnl(boolean SignIn) {
        signIn = SignIn;
        if(SignIn){
            pnlSignIn.setVisible(true);
            pnlSignUp.setVisible(false);
        }else{
            pnlSignIn.setVisible(false);
            pnlSignUp.setVisible(true);
        }
    }
    
    public JPanel getPanel(){
        return signIn ? pnlSignIn : pnlSignUp;
    }
    
    
   
}
