/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.view.administrator;

import domain.Administrator;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.io.IOException;
import javax.swing.JButton;

/**
 *
 * @author vidan
 */
public class MainFrameA extends javax.swing.JFrame {

    /**
     * Creates new form MainFrameA
     */
    public MainFrameA(Administrator administrator) throws IOException {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnExit = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnSwitchKlijenti = new javax.swing.JButton();
        btnSwichKnjige = new javax.swing.JButton();
        btnSwichNovaKnjiga = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        btnSwitchNoviKlijent = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(212, 221, 225));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 82, 82)));
        jPanel2.setPreferredSize(new java.awt.Dimension(696, 27));

        btnExit.setIcon(new javax.swing.ImageIcon("C:\\Users\\vidan\\Documents\\NetBeansProjects\\SeminarskiPS\\SSBiblioteka\\SSBibliotekaClient\\src\\images\\icons8_delete_16px.png")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 821, Short.MAX_VALUE)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btnExit)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(51, 82, 82));
        jPanel1.setPreferredSize(new java.awt.Dimension(155, 375));

        btnSwitchKlijenti.setBackground(new java.awt.Color(212, 221, 225));
        btnSwitchKlijenti.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        btnSwitchKlijenti.setForeground(new java.awt.Color(45, 48, 51));
        btnSwitchKlijenti.setIcon(new javax.swing.ImageIcon("C:\\Users\\vidan\\Documents\\NetBeansProjects\\SeminarskiPS\\SSBiblioteka\\SSBibliotekaClient\\src\\images\\icons8_user_24px.png")); // NOI18N
        btnSwitchKlijenti.setText("Klijenti");
        btnSwitchKlijenti.setPreferredSize(new java.awt.Dimension(155, 33));

        btnSwichKnjige.setBackground(new java.awt.Color(212, 221, 225));
        btnSwichKnjige.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        btnSwichKnjige.setForeground(new java.awt.Color(45, 48, 51));
        btnSwichKnjige.setIcon(new javax.swing.ImageIcon("C:\\Users\\vidan\\Documents\\NetBeansProjects\\SeminarskiPS\\SSBiblioteka\\SSBibliotekaClient\\src\\images\\icons8_book_26px.png")); // NOI18N
        btnSwichKnjige.setText("Knjige");

        btnSwichNovaKnjiga.setBackground(new java.awt.Color(212, 221, 225));
        btnSwichNovaKnjiga.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        btnSwichNovaKnjiga.setForeground(new java.awt.Color(45, 48, 51));
        btnSwichNovaKnjiga.setIcon(new javax.swing.ImageIcon("C:\\Users\\vidan\\Documents\\NetBeansProjects\\SeminarskiPS\\SSBiblioteka\\SSBibliotekaClient\\src\\images\\icons8_add_24px.png")); // NOI18N
        btnSwichNovaKnjiga.setText("Nova knjiga");

        btnLogOut.setBackground(new java.awt.Color(51, 82, 82));
        btnLogOut.setIcon(new javax.swing.ImageIcon("C:\\Users\\vidan\\Documents\\NetBeansProjects\\SeminarskiPS\\SSBiblioteka\\SSBibliotekaClient\\src\\images\\icons8_logout_rounded_up_30px.png")); // NOI18N
        btnLogOut.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(45, 48, 51), 6, true));

        btnSwitchNoviKlijent.setBackground(new java.awt.Color(212, 221, 225));
        btnSwitchNoviKlijent.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        btnSwitchNoviKlijent.setForeground(new java.awt.Color(45, 48, 51));
        btnSwitchNoviKlijent.setIcon(new javax.swing.ImageIcon("C:\\Users\\vidan\\Documents\\NetBeansProjects\\SeminarskiPS\\SSBiblioteka\\SSBibliotekaClient\\src\\images\\icons8_add_user_male_24px.png")); // NOI18N
        btnSwitchNoviKlijent.setText("Novi klijent");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSwichKnjige, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSwichNovaKnjiga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSwitchNoviKlijent, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSwitchKlijenti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnSwitchKlijenti, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSwichKnjige, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSwichNovaKnjiga, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSwitchNoviKlijent, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 203, Short.MAX_VALUE)
                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnSwichKnjige;
    private javax.swing.JButton btnSwichNovaKnjiga;
    private javax.swing.JButton btnSwitchKlijenti;
    private javax.swing.JButton btnSwitchNoviKlijent;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnExit() {
        return btnExit;
    }

    public void setBtnExit(JButton btnExit) {
        this.btnExit = btnExit;
    }

    public JButton getBtnLogOut() {
        return btnLogOut;
    }

    public void setBtnLogOut(JButton btnLogOut) {
        this.btnLogOut = btnLogOut;
    }

    public JButton getBtnSwichKnjige() {
        return btnSwichKnjige;
    }

    public void setBtnSwichKnjige(JButton btnSwichKnjige) {
        this.btnSwichKnjige = btnSwichKnjige;
    }

    public JButton getBtnSwichNovaKnjiga() {
        return btnSwichNovaKnjiga;
    }

    public void setBtnSwichNovaKnjiga(JButton btnSwichNovaKnjiga) {
        this.btnSwichNovaKnjiga = btnSwichNovaKnjiga;
    }

    public JButton getBtnSwitchKlijenti() {
        return btnSwitchKlijenti;
    }

    public void setBtnSwitchKlijenti(JButton btnSwitchKlijenti) {
        this.btnSwitchKlijenti = btnSwitchKlijenti;
    }

    public JButton getBtnSwitchNoviKlijent() {
        return btnSwitchNoviKlijent;
    }

    public void setBtnSwitchNoviKlijent(JButton btnSwitchNoviKlijent) {
        this.btnSwitchNoviKlijent = btnSwitchNoviKlijent;
    }


    
    

}
